name: Main

on: 
  push:
  schedule:
    - cron: '0 2 * * *'

jobs:
  windows:
    name: Windows
    runs-on: windows-2022
    defaults:
      run:
        shell: powershell
        # working-directory: ./scripts


    steps:

    # - name: Install SWIG
    #   run: |
    #     choco install swig --version 4.1.1 --yes --limit-output --allow-downgrade
    #     swig -swiglib
      

    - name: Install Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'
        

    - name: Upgrade 
      run: |
        python3 -m pip install --upgrade pip
        python3 -m pip install setuptools wheel


    # - name: Checkout repository
    #   uses: actions/checkout@v4


    - name: Checkout cppy
      uses: actions/checkout@v4
      with:
         repository: nucleic/cppy
         path: cppy


    - name: Checkout kiwi
      uses: actions/checkout@v4
      with:
         repository: nucleic/kiwi
         path: kiwi


    - name: Build 
      id: build
      run: |
        mkdir $env:GITHUB_WORKSPACE\\build
        chdir $env:GITHUB_WORKSPACE\\build


    - name: Build wheel file
      run: |
        chdir $env:GITHUB_WORKSPACE/cppy
        python setup.py bdist_wheel
        chdir $env:GITHUB_WORKSPACE/cppy/dist
        python -m pip install cppy-0.0.0-py3-none-any.whl
        # move $env:GITHUB_WORKSPACE/cppy/dist/*.whl ~

        chdir $env:GITHUB_WORKSPACE/kiwi
        python setup.py bdist_wheel
        move $env:GITHUB_WORKSPACE/kiwi/dist/*.whl ~

    - name: Upload 
      uses: actions/upload-artifact@v4
      with:
        name: kiwi_win64_py312
        path: ~/*.whl
        compression-level: 0
