name: Main

on: 
  push:
  schedule:
    - cron: '0 2 * * *'

jobs:
  windows:
    name: Windows
    runs-on: windows-2022
    defaults:
      run:
        shell: powershell

    steps:

    - name: Install Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'
        

    - name: Upgrade 
      run: |
        python3 -m pip install --upgrade pip
        python3 -m pip install setuptools wheel

    # - name: Checkout cppy
    #   uses: actions/checkout@v4
    #   with:
    #      repository: nucleic/cppy
    #      path: cppy


    # - name: Checkout kiwi
    #   uses: actions/checkout@v4
    #   with:
    #      repository: nucleic/kiwi
    #      path: kiwi


    - name: Build
      run: |
        # chdir $env:GITHUB_WORKSPACE/cppy
        # python setup.py bdist_wheel
        # chdir $env:GITHUB_WORKSPACE/cppy/dist
        # python -m pip install cppy-0.0.0-py3-none-any.whl
        # move $env:GITHUB_WORKSPACE/cppy/dist/*.whl ~

        # python -m pip install cppy

        # chdir $env:GITHUB_WORKSPACE/kiwi
        # python setup.py bdist_wheel
        # move $env:GITHUB_WORKSPACE/kiwi/dist/*.whl ~

        python -m pip install kiwisolver --no-binary kiwisolver

        # pip cache dir kiwisolver

        # dir c:\users\runneradmin\appdata\local\pip\cache\wheels\74\5c\a8\b3b464707683a040699b7b954101906e4fbd6cde4bf19da1d2

    - name: Copy
      shell: python
      run: |
        import os
        for root,dirs,files in os.walk('c:/users/runneradmin/appdata/local/pip/cache/wheels'):
            for file in files:
                if file.startswith('kiwisolver') and file.endswith('.whl'):
                    break
                    kiwi = os.path.join(root,file)
        import shutil
        shutil.move(kiwi, 'c:/'+file)

    - name: Upload 
      uses: actions/upload-artifact@v4
      with:
        name: kiwi_win64_py312
        path: c:/*.whl
        compression-level: 0
